-- ================================================================
-- KÉSZLETGAZDÁLKODÁS – SAP HANA ADATBÁZIS SÉMA
-- Projekt: SAP UI5 V2 → Railway POC
-- Verzió:  1.0  |  2025-06
-- ----------------------------------------------------------------
-- Bérlői izolálás: SAP HANA Cloud esetén minden bérlő saját
-- sémájában tárolja a táblákat (pl. TENANT_T001.INV_PRODUCTS).
-- POC környezetben közös (alapértelmezett) sémában futnak.
-- ================================================================

-- ----------------------------------------------------------------
-- 1. INV_CATEGORIES – Termékkategóriák
-- ----------------------------------------------------------------
CREATE TABLE INV_CATEGORIES (
    category_id     VARCHAR(20)  NOT NULL,
    category_name   VARCHAR(100) NOT NULL,
    description     VARCHAR(255),
    CONSTRAINT pk_inv_categories PRIMARY KEY (category_id)
);

-- ----------------------------------------------------------------
-- 2. INV_SUPPLIERS – Szállítók
-- ----------------------------------------------------------------
CREATE TABLE INV_SUPPLIERS (
    supplier_id       VARCHAR(20)   NOT NULL,
    supplier_name     VARCHAR(150)  NOT NULL,
    contact_email     VARCHAR(150),
    default_lead_days INTEGER       NOT NULL DEFAULT 14,
    reliability_score DECIMAL(5,2)  NOT NULL DEFAULT 80.0,
    CONSTRAINT pk_inv_suppliers PRIMARY KEY (supplier_id)
);

-- ----------------------------------------------------------------
-- 3. INV_PRODUCTS – Termékek (törzstábla)
-- ----------------------------------------------------------------
CREATE TABLE INV_PRODUCTS (
    product_id       VARCHAR(20)    NOT NULL,
    product_code     VARCHAR(50)    NOT NULL,
    product_name     VARCHAR(200)   NOT NULL,
    category_id      VARCHAR(20)    NOT NULL,
    unit             VARCHAR(30)    NOT NULL,
    unit_price       DECIMAL(12,2)  NOT NULL,
    supplier_id      VARCHAR(20)    NOT NULL,
    lead_time_days   INTEGER        NOT NULL,
    min_stock_level  DECIMAL(12,2)  NOT NULL,
    max_stock_level  DECIMAL(12,2)  NOT NULL,
    reorder_quantity DECIMAL(12,2)  NOT NULL,
    active           BOOLEAN        DEFAULT TRUE,
    CONSTRAINT pk_inv_products     PRIMARY KEY (product_id),
    CONSTRAINT uq_product_code     UNIQUE (product_code),
    CONSTRAINT fk_prod_category    FOREIGN KEY (category_id) REFERENCES INV_CATEGORIES(category_id),
    CONSTRAINT fk_prod_supplier    FOREIGN KEY (supplier_id) REFERENCES INV_SUPPLIERS(supplier_id)
);

-- ----------------------------------------------------------------
-- 4. INV_STOCK_MOVEMENTS – Készletmozgások naplója
--    quantity: POZITÍV = bevételezés (IN/RETURN), NEGATÍV = kiadás (OUT)
-- ----------------------------------------------------------------
CREATE TABLE INV_STOCK_MOVEMENTS (
    movement_id   INTEGER       NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    product_id    VARCHAR(20)   NOT NULL,
    movement_date DATE          NOT NULL,
    quantity      DECIMAL(12,2) NOT NULL,
    movement_type VARCHAR(20)   NOT NULL,
    reference_doc VARCHAR(100),
    created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_inv_movements     PRIMARY KEY (movement_id),
    CONSTRAINT fk_mov_product       FOREIGN KEY (product_id) REFERENCES INV_PRODUCTS(product_id),
    CONSTRAINT chk_movement_type    CHECK (movement_type IN ('IN','OUT','RETURN','ADJUSTMENT'))
);

-- Teljesítményindex a leggyakoribb lekérdezési mintákhoz
CREATE INDEX idx_inv_mov_prod_date ON INV_STOCK_MOVEMENTS (product_id, movement_date);
CREATE INDEX idx_inv_mov_type_date ON INV_STOCK_MOVEMENTS (movement_type, movement_date);

-- ----------------------------------------------------------------
-- 5. INV_CURRENT_STOCK – Aktuális készletszintek (pillanatkép)
-- ----------------------------------------------------------------
CREATE TABLE INV_CURRENT_STOCK (
    product_id       VARCHAR(20)   NOT NULL,
    current_quantity DECIMAL(12,2) NOT NULL,
    warehouse_zone   VARCHAR(20),
    last_updated     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_inv_current_stock PRIMARY KEY (product_id),
    CONSTRAINT fk_stock_product     FOREIGN KEY (product_id) REFERENCES INV_PRODUCTS(product_id)
);

-- ================================================================
-- NÉZETEK (VIEWS)
-- ================================================================

-- ----------------------------------------------------------------
-- v_avg_daily_demand
-- Átlagos napi kereslet (OUT mozgások) az elmúlt 30/60/90 napra.
-- A horizont_days paramétert az alkalmazásréteg kezeli;
-- ez a nézet mind a három ablakot előszámítja.
-- ----------------------------------------------------------------
CREATE VIEW v_avg_daily_demand AS
SELECT
    p.product_id,
    p.product_code,
    p.product_name,
    p.category_id,
    c.category_name,
    p.unit,
    p.unit_price,
    p.supplier_id,
    s.supplier_name,
    s.reliability_score,
    p.lead_time_days,
    p.min_stock_level,
    p.max_stock_level,
    p.reorder_quantity,
    -- Átlagos napi kereslet az elmúlt 30 napban
    COALESCE(
        (SELECT SUM(ABS(m30.quantity)) FROM INV_STOCK_MOVEMENTS m30
         WHERE m30.product_id = p.product_id
           AND m30.movement_type = 'OUT'
           AND m30.movement_date >= ADD_DAYS(CURRENT_DATE, -30)
        ) / 30.0,
        0.0
    ) AS avg_daily_demand_30d,
    -- Átlagos napi kereslet az elmúlt 60 napban
    COALESCE(
        (SELECT SUM(ABS(m60.quantity)) FROM INV_STOCK_MOVEMENTS m60
         WHERE m60.product_id = p.product_id
           AND m60.movement_type = 'OUT'
           AND m60.movement_date >= ADD_DAYS(CURRENT_DATE, -60)
        ) / 60.0,
        0.0
    ) AS avg_daily_demand_60d,
    -- Átlagos napi kereslet az elmúlt 90 napban
    COALESCE(
        (SELECT SUM(ABS(m90.quantity)) FROM INV_STOCK_MOVEMENTS m90
         WHERE m90.product_id = p.product_id
           AND m90.movement_type = 'OUT'
           AND m90.movement_date >= ADD_DAYS(CURRENT_DATE, -90)
        ) / 90.0,
        0.0
    ) AS avg_daily_demand_90d,
    -- Trend: elmúlt 30 nap vs megelőző 30 nap
    COALESCE(
        (SELECT SUM(ABS(ml30.quantity)) FROM INV_STOCK_MOVEMENTS ml30
         WHERE ml30.product_id = p.product_id
           AND ml30.movement_type = 'OUT'
           AND ml30.movement_date >= ADD_DAYS(CURRENT_DATE, -30)
        ) / 30.0,
        0.0
    ) /
    NULLIF(
        COALESCE(
            (SELECT SUM(ABS(mp30.quantity)) FROM INV_STOCK_MOVEMENTS mp30
             WHERE mp30.product_id = p.product_id
               AND mp30.movement_type = 'OUT'
               AND mp30.movement_date >= ADD_DAYS(CURRENT_DATE, -60)
               AND mp30.movement_date <  ADD_DAYS(CURRENT_DATE, -30)
            ) / 30.0,
            0.0
        ),
        0.0
    ) AS demand_trend_ratio
FROM INV_PRODUCTS p
JOIN INV_CATEGORIES c ON p.category_id = c.category_id
JOIN INV_SUPPLIERS  s ON p.supplier_id  = s.supplier_id
WHERE p.active = TRUE;

-- ----------------------------------------------------------------
-- v_days_until_stockout
-- Napok száma a készlethiányig, az aktuális készletszint és
-- az elmúlt 30 nap átlagos napi kereslete alapján.
-- ----------------------------------------------------------------
CREATE VIEW v_days_until_stockout AS
SELECT
    d.product_id,
    d.product_name,
    d.category_id,
    d.category_name,
    d.unit,
    d.unit_price,
    d.supplier_name,
    d.reliability_score,
    d.lead_time_days,
    d.min_stock_level,
    d.max_stock_level,
    d.reorder_quantity,
    cs.current_quantity,
    cs.warehouse_zone,
    d.avg_daily_demand_30d AS avg_daily_demand,
    d.avg_daily_demand_60d,
    d.avg_daily_demand_90d,
    d.demand_trend_ratio,
    CASE
        WHEN d.avg_daily_demand_30d > 0
        THEN ROUND(cs.current_quantity / d.avg_daily_demand_30d, 1)
        ELSE 9999
    END AS days_until_stockout,
    CASE
        WHEN d.demand_trend_ratio IS NULL   THEN 'STABLE'
        WHEN d.demand_trend_ratio > 1.05    THEN 'INCREASING'
        WHEN d.demand_trend_ratio < 0.95    THEN 'DECREASING'
        ELSE 'STABLE'
    END AS demand_trend
FROM v_avg_daily_demand d
JOIN INV_CURRENT_STOCK cs ON d.product_id = cs.product_id;

-- ----------------------------------------------------------------
-- v_reorder_suggestions
-- Újrarendelési javaslatok – csak az azonnali beavatkozást
-- igénylő termékek (CRITICAL és WARNING státusz).
-- ----------------------------------------------------------------
CREATE VIEW v_reorder_suggestions AS
SELECT
    ds.product_id,
    ds.product_name,
    ds.category_name,
    ds.current_quantity,
    ds.unit,
    ds.avg_daily_demand,
    ds.days_until_stockout,
    ds.demand_trend,
    ds.lead_time_days,
    ds.max_stock_level,
    ds.min_stock_level,
    ds.unit_price,
    ds.supplier_name,
    ds.reliability_score,
    ds.warehouse_zone,
    GREATEST(ds.max_stock_level - ds.current_quantity, 0) AS suggested_quantity,
    GREATEST(ds.max_stock_level - ds.current_quantity, 0) * ds.unit_price AS estimated_value_huf,
    CASE
        WHEN ds.current_quantity > ds.max_stock_level   THEN 'EXCESS'
        WHEN ds.days_until_stockout <= ds.lead_time_days THEN 'CRITICAL'
        WHEN ds.days_until_stockout <= (ds.lead_time_days + 7) THEN 'WARNING'
        ELSE 'STABLE'
    END AS classification,
    ADD_DAYS(
        CURRENT_DATE,
        CAST(GREATEST(ROUND(ds.days_until_stockout, 0) - ds.lead_time_days, 0) AS INTEGER)
    ) AS latest_order_date
FROM v_days_until_stockout ds
WHERE ds.current_quantity > ds.max_stock_level
   OR ds.days_until_stockout <= (ds.lead_time_days + 7)
ORDER BY
    CASE
        WHEN ds.current_quantity > ds.max_stock_level    THEN 3
        WHEN ds.days_until_stockout <= ds.lead_time_days THEN 1
        ELSE 2
    END,
    ds.days_until_stockout;

-- ================================================================
-- ELLENŐRZÉS – sorok száma az egyes táblákban
-- ================================================================
SELECT 'INV_CATEGORIES'     AS tabla, COUNT(*) AS sorok FROM INV_CATEGORIES
UNION ALL
SELECT 'INV_SUPPLIERS',              COUNT(*)           FROM INV_SUPPLIERS
UNION ALL
SELECT 'INV_PRODUCTS',               COUNT(*)           FROM INV_PRODUCTS
UNION ALL
SELECT 'INV_STOCK_MOVEMENTS',        COUNT(*)           FROM INV_STOCK_MOVEMENTS
UNION ALL
SELECT 'INV_CURRENT_STOCK',          COUNT(*)           FROM INV_CURRENT_STOCK;
